server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
        username: admin
        password: admin
        instance:
          prefer-ip: true
          service-url: http://localhost:8080